[package]
name = "bitwarden-wasm"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
internal = ["bitwarden-json/internal"] # Internal testing methods
performance-testing = ["bitwarden-json/performance-testing"] # Performance testing methods

[dependencies]
js-sys = "0.3.63"
serde = {version = "1.0.163", features = ["derive"] }
wasm-bindgen = { version = "0.2.86", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.36"
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.18"

bitwarden-json = { path = "../bitwarden-json" }

[dev-dependencies]
wasm-bindgen-test = "0.3.36"

[profile.release]
lto = true
opt-level = "z"
