[package]
name = "bw"
version = "0.0.2"
edition = "2021"
rust-version = "1.60"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Password Manager CLI
"""
keywords = ["bitwarden", "password-manager", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
log = "0.4.18"
env_logger = "0.10.0"
color-eyre = "0.6"
inquire = "0.6.2"
uuid = { version = "^1.3.3", features = ["serde"] }
serde = "^1.0.163"
serde_json = "^1.0.96"
serde_yaml = "0.9"
bat = { version = "0.24.0", features = [
    "regex-onig",
], default-features = false }
chrono = { version = "0.4.26", features = [
    "clock",
    "std",
], default-features = false }
comfy-table = "^7.0.1"
supports-color = "2.0.0"

bitwarden = { path = "../bitwarden", version = "0.3.1", features = [
    "internal",
    "mobile",
] }
bitwarden-cli = { path = "../bitwarden-cli", version = "0.1.0" }

[dev-dependencies]
tempfile = "3.5.0"
