[package]
name = "bw"
version = "0.0.2"
edition = "2021"
rust-version = "1.60"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Password Manager CLI
"""
keywords = ["bitwarden", "password-manager", "cli"]

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
color-eyre = "0.6"
env_logger = "0.10.0"
inquire = "0.6.2"
log = "0.4.20"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }

bitwarden = { path = "../bitwarden", version = "0.3.1", features = [
    "internal",
    "mobile",
] }
bitwarden-cli = { path = "../bitwarden-cli", version = "0.1.0" }

[dev-dependencies]
tempfile = "3.5.0"
