[package]
name = "language-tests"
version = "0.5.0"
authors = ["Bitwarden Inc"]
edition = "2021"
rust-version = "1.75"
homepage = "https://bitwarden.com"
repository = "https://github.com/bitwarden/sdk"
license-file = "LICENSE"


[dependencies]
anyhow = "1.0.87"
bitwarden = { path = "../../crates/bitwarden",  features = ["secrets", "internal"] }
futures = "0.3.30"
serde = {version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.10.0", features = ["serde"] }
