[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "bitwarden-sdk"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
]
description = "Bitwarden Secrets Manager SDK'"
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [{ name = "Bitwarden Inc.", email = "hello@bitwarden.com" }]

[project.urls]
homepage = "https://bitwarden.com/products/secrets-manager"
repository = "https://github.com/bitwarden/sdk"

[tool.maturin]
module-name = "bitwarden_sdk"
bindings = "uniffi"
manifest-path = "../../crates/bitwarden-uniffi/Cargo.toml"
