[package]
name = "bws"
version = "0.2.1"
edition = "2021"
rust-version = "1.60"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager CLI
"""
keywords = ["bitwarden", "secrets-manager", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive", "env"] }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
log = "0.4.17"
bitwarden = { path = "../bitwarden", version = "0.2.1" }
env_logger = "0.10.0"
atty = "0.2"
thiserror = "1.0.38"
serde = "^1.0"
serde_json = "^1.0"
serde_yaml = "0.9"
bat = "0.22.1"
directories = "5.0.0"
color-eyre = "0.6"
toml = "0.7.1"
comfy-table = "^6.1"
chrono = "0.4.23"

[dev-dependencies]
tempfile = "3.3.0"
