[package]
name = "bws"
version = "0.3.1"
edition = "2021"
rust-version = "1.60"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager CLI
"""
keywords = ["bitwarden", "secrets-manager", "cli"]

[dependencies]
bat = { version = "0.24.0", features = [
    "regex-onig",
], default-features = false }
chrono = { version = "0.4.31", features = [
    "clock",
    "std",
], default-features = false }
clap = { version = "4.3.0", features = ["derive", "env", "string"] }
clap_complete = "4.3.2"
color-eyre = "0.6"
comfy-table = "^7.0.1"
directories = "5.0.1"
env_logger = "0.10.1"
log = "0.4.20"
regex = { version = "1.10.2", features = [
    "std",
    "perf",
], default-features = false }
serde = "^1.0.163"
serde_json = "^1.0.96"
serde_yaml = "0.9"
supports-color = "2.0.0"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
toml = "0.8.8"
uuid = { version = "^1.3.3", features = ["serde"] }

bitwarden = { path = "../bitwarden", version = "0.3.1", features = ["secrets"] }

[dev-dependencies]
tempfile = "3.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
