[package]
name = "bitwarden-json"
version = "0.2.0"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
JSON bindings for the Bitwarden Secret Manager SDK
"""
keywords = ["bitwarden", "secrets manager"]
categories = ["api-bindings"]
edition = "2021"
rust-version = "1.57"

[dependencies]
schemars = "0.8.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.92"

bitwarden = { path = "../bitwarden" }
