[package]
name = "bitwarden-json"
version = "0.3.0"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
JSON bindings for the Bitwarden Secret Manager SDK
"""
keywords = ["bitwarden", "secrets manager"]
categories = ["api-bindings"]
edition = "2021"
rust-version = "1.57"

[features]
default = ["use_native_tls"]

internal = ["bitwarden/internal"] # Internal testing methods
secrets = ["bitwarden/secrets"]   # Secrets manager API

# TLS backend selection
use_native_tls = ["bitwarden/use_native_tls"]
use_rustls = ["bitwarden/use_rustls"]

[dependencies]
log = ">=0.4.18, <0.5"
schemars = ">=0.8.12, <0.9"
serde = { version = ">=1.0, <2.0", features = ["derive"] }
serde_json = ">=1.0.96, <2.0"

bitwarden = { path = "../bitwarden", default-features = false }
