[package]
name = "bitwarden-api-identity"
version = "0.2.0"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Api bindings for the Bitwarden Identity API.
"""
keywords = ["bitwarden"]
categories = ["api-bindings"]
edition = "2018"

[dependencies]
serde = "^1.0.159"
serde_derive = "^1.0.159"
serde_json = "^1.0.95"
serde_repr = "^0.1.12"
url = "^2.3.1"
uuid = { version = "^1.0", features = ["serde"] }
[dependencies.reqwest]
version = "^0.11.16"
features = ["json", "multipart"]

[dev-dependencies]
