[package]
name = "bitwarden-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
color-eyre = "0.6"
inquire = "0.6.2"
supports-color = "3.0.0"
