[package]
name = "bitwarden"
version = "0.3.0"
authors = ["Bitwarden Inc"]
license-file = "LICENSE"
repository = "https://github.com/bitwarden/sdk"
homepage = "https://bitwarden.com"
description = """
Bitwarden Secrets Manager SDK
"""
keywords = ["bitwarden", "secrets-manager"]
edition = "2021"
rust-version = "1.57"

[features]
default = ["secrets"]

secrets = []  # Secrets manager API
internal = [] # Internal testing methods
mobile = []   # Mobile-specific features

stdweb = ["instant/stdweb"]
wasm-bindgen = ["instant/wasm-bindgen"]

[dependencies]
aes = ">=0.8.2, <0.9"
argon2 = { version = ">=0.5.0, <0.6", features = [
    "alloc",
], default-features = false }
assert_matches = ">=1.5.0, <2.0"
base64 = ">=0.21.2, <0.22"
cbc = { version = ">=0.1.2, <0.2", features = ["alloc"] }
chrono = { version = ">=0.4.26, <0.5", features = [
    "serde",
], default-features = false }
hkdf = ">=0.12.3, <0.13"
hmac = ">=0.12.1, <0.13"
instant = ">=0.1.12, <0.2"
lazy_static = ">=1.4.0, <2.0"
log = ">=0.4.18, <0.5"
num-bigint = ">=0.4, <0.5"
num-traits = ">=0.2.15, <0.3"
pbkdf2 = { version = ">=0.12.1, <0.13", default-features = false }
rand = ">=0.8.5, <0.9"
reqwest = { version = ">=0.11, <0.12", features = ["json"] }
rsa = ">=0.9.2, <0.10"
schemars = { version = ">=0.8, <0.9", features = ["uuid1", "chrono"] }
serde = { version = ">=1.0, <2.0", features = ["derive"] }
serde_json = ">=1.0.96, <2.0"
serde_qs = ">=0.12.0, <0.13"
serde_repr = ">=0.1.12, <0.2"
sha1 = ">=0.10.5, <0.11"
sha2 = ">=0.10.6, <0.11"
thiserror = ">=1.0.40, <2.0"
uuid = { version = ">=1.3.3, <2.0", features = ["serde"] }

# We don't use this directly (it's used by rand), but we need it here to enable WASM support
getrandom = { version = ">=0.2.9", features = ["js"] }

bitwarden-api-api = { path = "../bitwarden-api-api", version = "0.2.1" }
bitwarden-api-identity = { path = "../bitwarden-api-identity", version = "0.2.1" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["rt", "macros"] }
wiremock = "0.5.18"
