[package]
name = "bitwarden"
description = """
Bitwarden Secrets Manager SDK
"""
keywords = ["bitwarden", "secrets-manager"]

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[features]
default = ["secrets"]

internal = [
    "dep:bitwarden-exporters",
    "dep:bitwarden-generators",
    "bitwarden-core/internal",
] # Internal testing methods
no-memory-hardening = [
    "bitwarden-core/no-memory-hardening",
] # Disable memory hardening features
mobile = [
    "internal",
    "bitwarden-core/mobile",
    "bitwarden-crypto/mobile",
    "bitwarden-generators/mobile",
] # Mobile-specific features
secrets = ["bitwarden-core/internal", "dep:bitwarden-sm"] # Secrets manager API

[dependencies]
bitwarden-api-api = { workspace = true }
bitwarden-api-identity = { workspace = true }
bitwarden-core = { workspace = true }
bitwarden-crypto = { workspace = true }
bitwarden-exporters = { workspace = true, optional = true }
bitwarden-generators = { workspace = true, optional = true }
bitwarden-sm = { workspace = true, optional = true }
uuid = ">=1.3.3, <2"

[lints]
workspace = true
