[package]
name = "bitwarden-uniffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
env_logger = "0.10.0"
async-lock = "2.7.0"
openssl = { version = "0.10", features = ["vendored"] }
uniffi = "0.24.1"

bitwarden = { path = "../bitwarden", features = ["internal", "mobile"] }
