[package]
name = "bitwarden-uniffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[lib]
crate-type = ["staticlib", "cdylib"]
bench = false

[dependencies]
async-lock = "2.7.0"
env_logger = "0.10.0"
uniffi = "=0.24.1"

bitwarden = { path = "../bitwarden", features = ["mobile", "internal"] }

[build-dependencies]
uniffi = { version = "=0.24.1", features = ["build"] }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
