[package]
name = "bitwarden-uniffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[features]
docs = ["dep:schemars"] # Docs

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
async-lock = "3.3.0"
chrono = { version = ">=0.4.26, <0.5", features = [
    "serde",
    "std",
], default-features = false }
env_logger = "0.10.1"
schemars = { version = ">=0.8, <0.9", optional = true }
uniffi = "=0.26.1"

bitwarden = { path = "../bitwarden", features = ["mobile", "internal"] }
bitwarden-crypto = { path = "../bitwarden-crypto", version = "=0.1.0", features = [
    "mobile",
] }
bitwarden-generators = { path = "../bitwarden-generators", version = "=0.1.0", features = [
    "mobile",
] }

[build-dependencies]
uniffi = { version = "=0.26.1", features = ["build"] }
