[package]
name = "language-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0.87"
bitwarden = { workspace = true, features = ["secrets", "internal"] }
futures = "0.3.30"
serde = {version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.10.0", features = ["serde"] }

[lints]
workspace = true
