---
name: Build Swift Package

on:
  push:
    branches:
      - "rc"
      - "hotfix-rc-swift"
      - "master"
      - "DEVOPS-1525-swift-workflow-for-package-publishing"
    # paths:
      # - "languages/swift/**"


jobs:
  version:
    name: Get Version
    runs-on: ubuntu-22.04
    outputs:
      package_version: ${{ steps.retrieve-version.outputs.package_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Get Package Version
        id: retrieve-version
        run: |
          VERSION=$(grep -o '^version = ".*"' crates/bitwarden/Cargo.toml | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: macos-13
    needs: version
    env:
      _VERSION: ${{ needs.version.outputs.package_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # stable
        with:
          toolchain: 1.70.0

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0
        with:
          key: sdk-swift-cargo

      - name: Rustup target
        run: |
          rustup target install aarch64-apple-ios-sim
          rustup target install aarch64-apple-ios
          rustup target install x86_64-apple-ios

      - name: Build
        shell: bash
        working-directory: languages/swift
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload BitwardenFFI.xcframework artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: BitwardenFFI-${{ env._VERSION }}-${GITHUB_SHA:0:7}.xcframework
          path: languages/swift/BitwardenFFI.xcframework
          if-no-files-found: error
