name: Build Java SDK

on:
  push:
    branches:
      - main
      - rc
      - hotfix-rc
  pull_request:
  workflow_dispatch:

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_java:
    name: Build Java
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download Java schemas artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: sdk-schemas-java
          path: languages/java/src/main/java/bit/sdk/schema/

      - name: Setup Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: temurin
          java-version: 17

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: languages/java/src/main/resources/darwin-x86-64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: languages/java/src/main/resources/darwin-aarch64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: languages/java/src/main/resources/linux-x86-64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: languages/java/src/main/resources/win32-x86-64

      - name: Build Maven
        run: ./gradlew build
        working-directory: languages/java
