name: Build Rust Cross Platform

on:
  workflow_call:

jobs:
  build_rust:
    name: Build for ${{ matrix.settings.os }} ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.os }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-12
            target: x86_64-apple-darwin
          - os: macos-12
            target: aarch64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@f361669954a8ecfc00a3443f35f9ac8e610ffc06 # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

      - name: Add build architecture
        run: rustup target add ${{ matrix.settings.target }}

      - name: Build Rust
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo build --target ${{ matrix.settings.target }} --release

      - name: Upload Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: libbitwarden_c_files-${{ matrix.settings.target }}
          path: |
            target/${{ matrix.settings.target }}/release/*bitwarden_c*
