name: Build C++ SDK

on:
  push:
    branches:
      - main
      - rc
      - hotfix-rc

  pull_request:
  workflow_dispatch:


jobs:
  generate-schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build:
    name: Build
    needs: generate-schemas
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: install dependencies
        run: |
          sudo apt-get install -y nlohmann-json3-dev
          sudo apt-get install -y libboost-all-dev

          dpkg -L nlohmann-json3-dev
          dpkg -L libboost-all-dev

      - name: Download schemas
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: sdk-schemas-cpp
          path: languages/cpp/include

      - name: Build
        working-directory: languages/cpp
        run: |
          mkdir build
          cd build
          cmake .. -DNLOHMANN=/path/to/include/nlohmann -DBOOST=/path/to/include/boost -DTARGET=../../target/release/libbitwarden_c.dylib
          cmake --build .

      - name: Upload C++ package
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: libbitwarden_c.dylib
          path: languages/cpp/target/release/libbitwarden_c.dylib
