name: Build Go SDK

on:
  push:
    branches:
      - main
      - rc
      - hotfix-rc

  pull_request:

env:
  GO111MODULE: on
  GO_VERSION: "^1.21"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup Go environment
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: npm ci
        run: npm ci

      - name: Generate schemas
        run: npm run schemas

      - name: Build
        working-directory: languages/go
        run: go build -v ./...

      - name: Test
        working-directory: languages/go
        run: go test -v ./...
