name: Build .NET SDK

on:
  pull_request:
    branches:
      - master

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_dotnet:
    runs-on: ubuntu-22.04
    needs: [generate_schemas]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Download c# schemas artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.cs
          path: languages/csharp

      - name: Set up .NET Core
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          global-json-file: languages/csharp/global.json

      - name: Build .NET 6 Project
        working-directory: languages/csharp
        run: |
          dotnet restore
          dotnet build --configuration Release
