name: Build Rust Cross Platform

on:
  workflow_call:

jobs:
  build_rust:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-12
            target: x86_64-apple-darwin

          - os: macos-12
            target: aarch64-apple-darwin

          - os: windows-2022
            target: x86_64-pc-windows-msvc

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.settings.os }}

    name: Build for ${{ matrix.settings.os }} ${{ matrix.settings.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install rust
        uses: dtolnay/rust-toolchain@f361669954a8ecfc00a3443f35f9ac8e610ffc06 # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

      - name: Add build architecture
        run: |
          rustup target add ${{ matrix.settings.target }}

      - name: Build Rust
        run: cargo build --target ${{ matrix.settings.target }} --release
        env:
          RUSTFLAGS: "-D warnings"

      - name: Upload Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: libbitwarden_c_files-${{ matrix.settings.target }}
          path: |
            target/${{ matrix.settings.target }}/release/*bitwarden_c*
