---
name: Build WASM

on:
  pull_request:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: crates/bitwarden-wasm

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  wasm:
    name: Building @bitwarden/wasm
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Install dependencies
        run: npm i -g binaryen

      - name: Install rust
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          key: wasm-cargo-cache

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: ./build.sh -r

      - name: Upload artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: sdk-bitwarden-wasm
          path: ${{ github.workspace }}/languages/js/wasm/*
          if-no-files-found: error

      - name: Set version
        if: ${{ github.ref == 'refs/heads/main' }}
        # Fetches current version from registry and uses prerelease to bump it
        run: |
          npm version --no-git-tag-version $(npm view @bitwarden/sdk-wasm@latest version)
          npm version --no-git-tag-version prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/wasm

      - name: Publish NPM
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/wasm

  client:
    name: Building @bitwarden/sdk-client
    runs-on: ubuntu-22.04
    needs: generate_schemas

    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Retrieve schemas
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: schemas.ts
          path: ${{ github.workspace }}/languages/js/sdk-client/src/

      - name: npm ci
        run: npm ci
        working-directory: languages/js/sdk-client

      - name: build
        run: npm run build
        working-directory: languages/js/sdk-client

      - name: Set version
        # if: ${{ github.ref == 'refs/heads/main' }}
        # Fetches current version from registry and uses prerelease to bump it
        run: |
          npm version --no-git-tag-version $(npm view @bitwarden/sdk-client@latest version)
          npm version --no-git-tag-version prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/sdk-client

      - name: Publish NPM
        # if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/sdk-client
