name: Build Ruby SDK

on:
  pull_request:
    branches:
      - master

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_ruby:
    name: Build Ruby
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Download Ruby schemas artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.rb
          path: languages/ruby/lib/schemas.rb

      - name: Set up Ruby
        uses: actions/checkout@v2 # Use a valid version
        with:
          ref: main # Replace with the branch you want to check out
          path: languages/ruby
          
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Replace with your desired Ruby version

      - name: Install Bundler and dependencies
        working-directory: languages/ruby
        run: |
          gem install bundler
          bundle install
          gem build ruby-sdk.gemspec
          gem install ruby-sdk-0.1.0.gem

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: languages/ruby/lib/macos-x64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: languages/ruby/lib/macos-arm64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: languages/ruby/lib/ubuntu-x64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: languages/ruby/lib/windows-x64
