---
name: Build Rust crates

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "rc"
      - "hotfix-rc"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Building ${{matrix.package}} for - ${{ matrix.os }}

    runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        package:
          - bitwarden
          - bitwarden-api-api
          - bitwarden-api-identity

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.settings.target }}
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894 # v2.4.0

      - name: Build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: ${{ matrix.features }} -p ${{ matrix.package }} --release

      - name: Build Internal
        if: ${{ matrix.package == 'bitwarden' }}
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: ${{ matrix.features }} -p ${{ matrix.package }} --features internal --release

  release-dry-run:
    name: Release dry-run
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/head/master' || github.ref == 'ref/head/rc' || github.ref == 'ref/head/hotfix-rc' }}
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.settings.target }}
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894 # v2.4.0

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Cargo release dry run
        run: cargo-release release publish -p bitwarden-api-api -p bitwarden-api-identity -p bitwarden
