name: Build Java SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_java:
    name: Build Java
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download Java schemas artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: sdk-schemas-java
          path: languages/java/src/main/java/bit/sdk/schema/

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: languages/java/src/main/resources/darwin-x86-64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: languages/java/src/main/resources/darwin-aarch64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: languages/java/src/main/resources/linux-x86-64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: languages/java/src/main/resources/win32-x86-64

      - name: Publish Maven
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87 # v3.0.0
        with:
          arguments: publish
          build-root-directory: languages/java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
