---
    name: Build Test rustls-platform-verifier

    on:
      pull_request:
      push:
        branches:
          - "main"
          - "rc"
          - "hotfix-rc"
      workflow_dispatch:

    defaults:
      run:
        shell: bash

    jobs:
      build-windows:
        name: Build Windows
        runs-on: windows-2022
        steps:
          - name: Checkout repo
            uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

          - name: Build
            run: cargo build -p test-rustls-platform-verifier --release --target=x86_64-pc-windows-msvc

          - name: Upload artifact
            uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
            with:
             name: test-rustls-platform-verifier
             path: ./target/release/test-rustls-platform-verifier.exe
