---
name: Direct Minimum Version

on:
  pull_request:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  direct-minimal-versions:
    name: Check dependencies minimal versions for - ${{ matrix.settings.os }} - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          #- os: macos-12
          #  target: x86_64-apple-darwin

          #- os: macos-12
          #  target: aarch64-apple-darwin

          - os: windows-2022
            target: x86_64-pc-windows-msvc

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install rust
        uses: dtolnay/rust-toolchain@dc6353516c68da0f06325f42ad880f76a5e77ec9 # stable
        with:
          toolchain: nightly
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          key: dmv-${{ matrix.settings.target }}-cargo-${{ matrix.settings.os }}

      - name: cargo check direct-minimal-versions
        run: cargo check -Z direct-minimal-versions --all-features
