name: Generate schemas

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - rc
      - hotfix-rc

env:
  CARGO_TERM_COLOR: always

jobs:
  schemas:
    name: Generate schemas
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install rust
        uses: dtolnay/rust-toolchain@dc6353516c68da0f06325f42ad880f76a5e77ec9 # stable
        with:
          toolchain: stable

      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "16"

      - name: NPM setup
        run: npm ci

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: NPM Schemas
        run: npm run schemas

      - name: Upload ts schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: schemas.ts
          path: ${{ github.workspace }}/languages/js/sdk-client/src/schemas.ts
          if-no-files-found: error

      - name: Upload c# schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: schemas.cs
          path: ${{ github.workspace }}/languages/csharp/Bitwarden.Sdk/schemas.cs
          if-no-files-found: error

      - name: Upload python schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: schemas.py
          path: ${{ github.workspace }}/languages/python/bitwarden_sdk/schemas.py
          if-no-files-found: error

      - name: Upload ruby schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: schemas.rb
          path: ${{ github.workspace }}/languages/ruby/bitwarden_sdk_secrets/lib/schemas.rb
          if-no-files-found: error

      - name: Upload json schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: sdk-schemas-json
          path: ${{ github.workspace }}/support/schemas/*
          if-no-files-found: error

      - name: Upload Go schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: schemas.go
          path: ${{ github.workspace }}/languages/go/schema.go

      - name: Upload java schemas artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: sdk-schemas-java
          path: ${{ github.workspace }}/languages/java/src/main/java/com/bitwarden/sdk/schema/*
          if-no-files-found: error
