name: Lint

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Install rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: fmt
          args: -- --check

      - name: Set up Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "16"

      - name: NPM setup
        run: npm ci

      - name: Node Lint
        run: npm run lint

      - name: Verify Schemas are up to date
        run: |
          npm run schemas
          git diff --exit-code HEAD
          # Verify no untracked files
          if [ ! -z "$(git status --porcelain)" ]; then
            >&2 echo "Failed: Found untracked files!"
            exit 1
          fi
