name: Publish .NET NuGet
run-name: Publish .NET NuGet Package ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        required: true
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

env:
  _KEY_VAULT: "bitwarden-ci"

jobs:
  validate:
    name: Setup
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Branch check
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/rc" ]] && [[ "$GITHUB_REF" != "refs/heads/hotfix-rc" ]]; then
            echo "==================================="
            echo "[!] Can only release from the 'rc' or 'hotfix-rc' branches"
            echo "==================================="
            exit 1
          fi

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Get version
        id: version
        run: |
          VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: validate
    steps:
      - name: Download NuGet package
        uses: bitwarden/gh-actions/download-artifacts@main
        with:
          workflow: build-dotnet.yml
          workflow_conclusion: success
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
          artifacts: Bitwarden.Sdk.${{ needs.validate.outputs.version }}.nupkg
          path: ./nuget-output

      - name: Login to Azure - Prod Subscription
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: ${{ env._KEY_VAULT }}
          secrets: "nuget-api-key"

      - name: Publish NuGet Package
        if: ${{ inputs.release_type != 'Dry Run' }}
        env:
          NUGET_API_KEY: ${{ steps.retrieve-secrets.outputs.nuget-api-key }}
        run: dotnet nuget push ./nuget-output/*.nupkg -k ${{ env.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
