name: Publish Ruby SDK

on:
  push:
    branches:
      - main

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_ruby:
    name: Build Ruby
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.171.0
        with:
          ruby-version: 3.2

      - name: Download Ruby schemas artifact
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: schemas.rb
          path: languages/ruby/bitwarden_sdk_secrets/lib

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: temp/macos-x64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: temp/macos-arm64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: temp/linux-x64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: temp/windows-x64

      - name: Copy lib files
        run: |
          mkdir -p languages/ruby/bitwarden_sdk_secrets/lib/macos-arm64
          mkdir -p languages/ruby/bitwarden_sdk_secrets/lib/linux-x64
          mkdir -p languages/ruby/bitwarden_sdk_secrets/lib/macos-x64
          mkdir -p languages/ruby/bitwarden_sdk_secrets/lib/windows-x64

          platforms=("macos-arm64" "linux-x64" "macos-x64" "windows-x64")
          files=("libbitwarden_c.dylib" "libbitwarden_c.so" "libbitwarden_c.dylib" "bitwarden_c.dll")

          for ((i=0; i<${#platforms[@]}; i++)); do
            cp "temp/${platforms[$i]}/${files[$i]}" "languages/ruby/bitwarden_sdk_secrets/lib/${platforms[$i]}/${files[$i]}"
          done
        shell: bash

      - name: Build gem
        run: gem build bitwarden-sdk.gemspec
        working-directory: languages/ruby/bitwarden_sdk_secrets

      - name: Push gem to Rubygems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        working-directory: languages/ruby/bitwarden_sdk_secrets
