name: Publish Ruby SDK

on:
  pull_request:
    branches:
      - master

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_ruby:
    name: Build Ruby
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Ruby
        uses: ruby/setup-ruby@679e23d4a31bcf7cd0a69acd348e5f79e8c6b443 #
        with:
          ruby-version: 3.2

      - name: Download Ruby schemas artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.rb
          path: languages/ruby/lib

      - name: Download and Copy Libraries
        run: |
          PLATFORMS=("macos-x64" "macos-arm64" "ubuntu-x64" "windows-x64")
          ARTIFACT_NAMES=("libbitwarden_c_files-x86_64-apple-darwin" "libbitwarden_c_files-aarch64-apple-darwin" "libbitwarden_c_files-x86_64-unknown-linux-gnu" "libbitwarden_c_files-x86_64-pc-windows-msvc")

          mkdir -p languages/ruby/lib

          for i in {0..3}; do
            artifact_name="${ARTIFACT_NAMES[$i]}"
            platform="${PLATFORMS[$i]}"

            echo "Downloading and copying files for $platform"
            run_name="Download and Copy $platform"

            uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            with:
              name: "$artifact_name"
              path: "temp/$platform"

            case "$platform" in
              "macos-x64" | "macos-arm64")
                cp "temp/$platform/libbitwarden_c.dylib" "languages/ruby/lib/$platform/libbitwarden_c.dylib"
                ;;
              "ubuntu-x64")
                cp "temp/$platform/libbitwarden_c.so" "languages/ruby/lib/$platform/libbitwarden_c.so"
                ;;
              "windows-x64")
                cp "temp/$platform/bitwarden_c.dll" "languages/ruby/lib/$platform/bitwarden_c.dll"
                ;;
            esac

            echo "Files for $platform copied successfully"
          done
        shell: bash


      - name: Setup gem and release it
        run: |
          cd languages/ruby
          gem install bundler
          gem build *.gemspec
          gem install *.gem
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}\n" > $HOME/.gem/credentials
          gem push *.gem

