name: Deploy NuGet Package

on:
  workflow_dispatch:
    version_number:
      description: "New Version"
      required: true

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  deploy:
    runs-on: ubuntu-22.04
    needs: [generate_schemas, build_rust]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Download c# schemas artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: schemas.cs
          path: languages/csharp

      - name: Set up .NET Core
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          global-json-file: languages/csharp/global.json

      - name: Download macos-latest-x64 files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-macos-latest-x64
          path: languages/csharp/macos-latest-x64

      - name: Download macos-latest-arm64 files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-macos-latest-arm64
          path: languages/csharp/macos-latest-arm64

      - name: Download ubuntu-latest-x64 files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-ubuntu-latest-x64
          path: languages/csharp/ubuntu-latest-x64

      - name: Download windows-latest-x64 files
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libbitwarden_c_files-windows-latest-x64
          path: languages/csharp/windows-latest-x64

      - name: Pack NuGet Package
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: |
          cd languages/csharp
          dotnet pack --configuration Release -p:PackageID=BitwardenSdk -p:Version=${VERSION} --output ./nuget-output /nologo /v:n

      - name: Publish NuGet Package
        run: dotnet nuget push ./languages/csharp/nuget-output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
