name: Rust tests

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "rc"
      - "hotfix-rc"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - test
      - wasm
    steps:
      - run: exit 0

  test:
    name: ${{ matrix.os }} / ${{matrix.target || 'default' }}

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install rust
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f # v2.5.1

      - name: Test
        run: cargo test --all-features

  wasm:
    name: WASM

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install rust
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f # v2.5.1

      - name: Check
        run: cargo check -p bitwarden-wasm --target wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Wasm-pack test firefox
        run: wasm-pack test --headless --firefox crates/bitwarden-wasm

      - name: Wasm-pack test chrome
        run: wasm-pack test --headless --chrome crates/bitwarden-wasm
